import mp3Type from "~/assets/audio/mp3Type";

const apiMusicMaker = {
  musicMakerList: [
    {
      id: "Suboi",
      makerAvatar:
        "https://avatar-ex-swe.nixcdn.com/singer/avatar/2018/07/19/8/1/6/a/1531989394829_600.jpg",
      makerName: "Suboi",
      role: "rapper",
      priority: true,
      singles: [
        {
          id: "su_troiCho",
          avatar:
            "https://photo-resize-zmp3.zmdcdn.me/w256_r1x1_jpeg/avatars/1/5/a/e/15ae72f637fd1d941a934b3edcf1ac39.jpg",
          title: "Trời Cho",
          mainMusicMaker: "Suboi",
          stageName: "Suboi ft. Touliver",
          type: "Single",
          genre: "Rap/HipHop",
          releaseDay: "2024-10-07",
          streamed: 0,
          trend: false,
          link: mp3Type[
            `MusicMaker/Suboi/singletracks/Trời Cho feat Hoàng Touliver`
          ],
          lyric: "",
        },
        {
          id: "su_doi",
          avatar:
            "https://static.tuoitre.vn/tto/i/s626/2016/03/10/suboi-doi-mv-1457581497.jpg",
          title: "Đời",
          mainMusicMaker: "Suboi",
          stageName: "Suboi",
          type: "Single",
          genre: "Rap/HipHop",
          releaseDay: "2024-10-10",
          streamed: 0,
          trend: false,
          link: mp3Type[`MusicMaker/Suboi/singletracks/Suboi  Đời`],
          lyric: "",
        },
        {
          id: "su_dauThienHa",
          avatar:
            "https://bloganchoi.com/wp-content/uploads/2024/03/loi-bai-hat-dau-thien-ha-lyric-suboi-1-696x696.jpg",
          title: "Dâu Thiên Hạ",
          mainMusicMaker: "Suboi",
          stageName: "Suboi",
          type: "Single",
          genre: "Rap/HipHop",
          releaseDay: "2024-10-12",
          streamed: 0,
          trend: false,
          link: mp3Type[`MusicMaker/Suboi/singletracks/Suboi  Dâu Thiên Hạ`],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "NO_NE",
          albumAvatar:
            "https://i1.sndcdn.com/artworks-aQq93a78hKXYoQ6L-5ijgkA-t500x500.jpg",
          albumPerformer: "Suboi",
          albumName: "Album - No Nê",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          releaseDay: "2023-10-25",
          tracks: [
            {
              id: "su_NoNe01",
              avatar:
                "https://i1.sndcdn.com/artworks-aQq93a78hKXYoQ6L-5ijgkA-t500x500.jpg",
              type: "Album",
              title: "Công",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  CÔNG`],
              lyric: "",
            },
            {
              id: "su_NoNe02",
              type: "Album",
              type: "Album",
              title: "Cho Không",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi CHO KHÔNG`],
              lyric: "",
            },
            {
              id: "su_NoNe03",
              type: "Album",
              title: `N-Sao`,
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  NSAO`],
              lyric: "",
            },
            {
              id: "su_NoNe04",
              type: "Album",
              title: "Sickerrr",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  SICKERRR`],
              lyric: "",
            },
            {
              id: "su_NoNe05",
              type: "Album",
              title: "Best Friend",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  Best Friend`],
              lyric: "",
            },
            {
              id: "su_NoNe06",
              type: "Album",
              title: "Bet On Me",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  BET ON ME`],
              lyric: "",
            },
            {
              id: "su_NoNe07",
              type: "Album",
              title: "Lava",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  LAVA`],
              lyric: "",
            },
            {
              id: "su_NoNe08",
              type: "Album",
              title: "Ngày Lại Ngày",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[
                `MusicMaker/Suboi/albums/NoNe/Suboi  NGÀY LẠI NGÀY`
              ],
              lyric: "",
            },
            {
              id: "su_NoNe09",
              type: "Album",
              title: "Diều",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: false,
              link: mp3Type[`MusicMaker/Suboi/albums/NoNe/Suboi  DIỀU`],
              lyric: "",
            },
            {
              id: "su_NoNe10",
              type: "Album",
              title: "Công (Dance Remix)",
              mainMusicMaker: "Suboi",
              stageName: "Suboi",
              name: "Album - No Nê",
              genre: "Rap/HipHop",
              releaseDay: "2023-10-12",
              streamed: 0,
              trend: true,
              link: mp3Type[
                `MusicMaker/Suboi/albums/NoNe/Suboi CÔNG Dance Remix`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "Rhymastic",
      makerAvatar:
        "https://avatar-ex-swe.nixcdn.com/singer/avatar/2022/09/16/2/e/3/c/1663304448274_600.jpg",
      makerName: "Rhymastic",
      role: "rapper" + "/" + "musicProducer",
      priority: true,
      singles: [
        {
          id: "rhym_Lac",
          avatar:
            "https://avatar-ex-swe.nixcdn.com/song/2022/06/22/2/2/2/d/1655865432491_640.jpg",
          title: "Lạc",
          mainMusicMaker: "Rhymastic",
          stageName: "Rhymastic",
          type: "Single",
          genre: "Rap/HipHop",
          releaseDay: "2024-10-06",
          streamed: 0,
          trend: false,
          link: mp3Type[`MusicMaker/Rhymastic/singletracks/LẠC  Rhymastic`],
          lyric: "",
        },
        {
          id: "rhym_Treasure",
          avatar:
            "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/covers/6/d/6d9bfab656c9be37b3ef972b8c9dd291_1503659621.jpg",
          title: "Treasure",
          mainMusicMaker: "Rhymastic",
          stageName: "Rhymastic",
          type: "Single",
          genre: "Pop",
          releaseDay: "2024-10-09",
          streamed: 0,
          trend: false,
          link: mp3Type[
            `MusicMaker/Rhymastic/singletracks/Rhymastic  Treasure Official Lyric Video`
          ],
          lyric: "",
        },
        {
          id: "rhym_Y5",
          avatar:
            "https://kenh14cdn.com/zoom/600_315/2017/photo1513197004779-1513197004779.jpg",
          title: "YÊU 5",
          mainMusicMaker: "Rhymastic",
          stageName: "Rhymastic",
          type: "Single",
          genre: "Pop",
          releaseDay: "2024-05-20",
          streamed: 50000,
          trend: true,
          link: mp3Type[`MusicMaker/Rhymastic/singletracks/YEU 5  Rhymastic`],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "LO_V6",
          albumAvatar:
            "https://i.scdn.co/image/ab67616d0000b273d98135e509a6271e6d1605a7",
          albumPerformer: "Rhymastic",
          albumName: "Album - LOV6 (EP)",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2022-09-15",
          tracks: [
            {
              id: "rhym_Lov601",
              type: "Album",
              title: "Y6U",
              avatar:
                "https://i.scdn.co/image/ab67616d0000b273d98135e509a6271e6d1605a7",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6 (EP)",
              genre: "RnB",
              releaseDay: "2023-08-25",
              streamed: 0,
              trend: true,
              link: mp3Type[`MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Y6U`],
              lyric: "",
            },
            {
              id: "rhym_Lov602",
              type: "Album",
              title: "Lía La Lía Lo",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6",
              genre: "Pop",
              releaseDay: "2023-08-25",
              streamed: 0,
              trend: false,
              link: mp3Type[
                `MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Líu La Líu Lo`
              ],
              lyric: "",
            },
            {
              id: "rhym_Lov603",
              type: "Album",
              title: "Side Effects",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6",
              genre: "RnB/HipHop",
              releaseDay: "2023-08-25",
              streamed: 0,
              trend: false,
              link: mp3Type[
                `MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Side Effects feat Touliver  BWine`
              ],
              lyric: "",
            },
            {
              id: "rhym_Lov604",
              type: "Album",
              title: "Ngổn Ngang",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6",
              genre: "RnB",
              releaseDay: "2023-08-25",
              streamed: 0,
              trend: false,
              link: mp3Type[
                `MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Ngổn Ngang`
              ],
              lyric: "",
            },
            {
              id: "rhym_Lov605",
              type: "Album",
              title: "Vẫn Yêu",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6",
              genre: "RnB",
              releaseDay: "2023-08-25",
              streamed: 0,
              trend: false,
              link: mp3Type[
                `MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Vẫn Yêu`
              ],
              lyric: "",
            },
            {
              id: "rhym_Lov606",
              type: "Album",
              title: "Thêm Đứa Nữa",
              mainMusicMaker: "Rhymastic",
              stageName: "Rhymastic",
              name: "Album - LOV6",
              genre: "Electro-disco",
              releaseDay: "2023-08-25",
              streamed: 1532,
              trend: false,
              link: mp3Type[
                `MusicMaker/Rhymastic/albums/LOV6/Rhymastic  Thêm Đứa Nữa`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "Touliver",
      makerAvatar: "https://cdn-www.vinid.net/ed96bcd6-touliver-1.jpg",
      makerName: "Touliver",
      role: "dj" + "/" + "musicProducer",
      priority: true,
      singles: [
        {
          id: "tou_GetIt",
          avatar:
            "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/1/4/1/b/141b9f990d714085e3a23fd8a42be625.jpg",
          title: "Get It",
          mainMusicMaker: "Touliver",
          stageName: "Touliver x Nimbia",
          type: "Single",
          genre: "Dance",
          releaseDay: "2024-10-02",
          streamed: 6032,
          trend: true,
          link: mp3Type[
            `MusicMaker/Touliver/singletracks/Touliver x Nimbia  Get It`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "J.Sheon",
      makerAvatar:
        "https://yt3.googleusercontent.com/jd9_c5NiLJ1tXXwRpkDo1r-NqZ_IiXFJFAULwqQZrw_n4YRj0Omo4jTAMQFSm2u9PVc3AiZSgg=s900-c-k-c0x00ffffff-no-rj",
      makerName: "J.Sheon",
      role: "singer",
      priority: false,
      singles: [
        {
          id: "jshe_DontAsk",
          avatar: "https://i.ytimg.com/vi/tRa3fOlnN7k/maxresdefault.jpg",
          title: "Don't Ask (別問很可怕)",
          mainMusicMaker: "J.Sheon",
          stageName: "J.Sheon",
          type: "Single",
          genre: "RnB Soul",
          releaseDay: "2024-10-05",
          streamed: 5595,
          trend: false,
          link: mp3Type[
            `MusicMaker/J.Sheon/singletracks/JSheon  Dont Ask 別問很可怕`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "Perfume",
      makerAvatar:
        "https://i.scdn.co/image/ab6761610000e5eb3955d594fd646c2b77f2ae03",
      makerName: "Perfume",
      role: "band",
      priority: false,
      singles: [
        {
          id: "per_SpinningWorld",
          avatar:
            "https://i.scdn.co/image/ab67616d0000b273de342f1d1fc6c3de3f6e5d1e",
          title: "Spinning World",
          mainMusicMaker: "Perfume",
          stageName: "Perfume",
          type: "Single",
          genre: "Electronic",
          releaseDay: "2024-10-12",
          streamed: 2023,
          trend: false,
          link: mp3Type[
            `MusicMaker/Perfume/singletracks/Perfume Spinning World`
          ],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "Level_3",
          albumAvatar:
            "https://draw.acharts.net/cover/80760-54d08c7965c19-l.jpg",
          albumPerformer: "Perfume",
          albumName: "Album - Level 3",
          mode: "AlbumList",
          rating: "rating",
          rate: 3,
          albumType: "Album",
          releaseDay: "2013-10-01",
          tracks: [
            {
              id: "per_lev301",
              avatar:
                "https://draw.acharts.net/cover/80760-54d08c7965c19-l.jpg",
              type: "Album",
              type: "Album",
              title: "Enter The Sphere",
              mainMusicMaker: "Perfume",
              stageName: "Perfume",
              name: "Album - Level 3",
              name: "Album - Level 3",
              genre: "Electro Pop",
              releaseDay: "2023-12-18",
              streamed: 3320,
              trend: false,
              link: mp3Type[
                `MusicMaker/Perfume/albums/LEVEL3/Enter the sphere`
              ],
              lyric: "",
            },
            {
              id: "per_lev302",
              type: "Album",
              title: "Spring of life (Album Mix)",
              mainMusicMaker: "Perfume",
              stageName: "Perfume",
              name: "Album - Level 3",
              genre: "Electro Pop",
              releaseDay: "2023-12-18",
              streamed: 2678,
              trend: false,
              link: mp3Type[
                `MusicMaker/Perfume/albums/LEVEL3/Spring of life Albummix`
              ],
              lyric: "",
            },
            {
              id: "per_lev303",
              type: "Album",
              title: "Magic of love (Album Mix)",
              mainMusicMaker: "Perfume",
              stageName: "Perfume",
              name: "Album - Level 3",
              genre: "Electro Pop",
              releaseDay: "2023-12-18",
              streamed: 1385,
              trend: false,
              link: mp3Type[
                `MusicMaker/Perfume/albums/LEVEL3/Magic of love Albummix`
              ],
              lyric: "",
            },
            {
              id: "per_lev304",
              type: "Album",
              title: "Clockwork",
              mainMusicMaker: "Perfume",
              stageName: "Perfume",
              name: "Album - Level 3",
              genre: "Electro Pop",
              releaseDay: "2023-12-18",
              streamed: 2685,
              trend: false,
              link: mp3Type[
                `MusicMaker/Perfume/albums/LEVEL3/LEVEL 3  Clockwork`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "BIBI",
      makerAvatar:
        "https://kenh14cdn.com/203336854389633024/2024/5/15/photo-2-1715757381263983732539.jpg",
      makerName: "BIBI",
      role: "singer",
      priority: false,
      singles: [
        {
          id: "bi_AnimalFarm",
          avatar:
            "https://images.genius.com/ea9cd6fef54ecdc755d6b10be33fda43.1000x1000x1.png",
          title: "Animal Farm (가면무도회)",
          mainMusicMaker: "BIBI",
          stageName: "BIBI",
          type: "Single",
          genre: "Pop",
          releaseDay: "2024-10-08",
          streamed: 3585,
          trend: false,
          link: mp3Type[
            `MusicMaker/BIBI/singletracks/비비 BIBI  가면무도회 Animal Farm`
          ],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "L_I_A_B",
          albumAvatar:
            "https://cdns-images.dzcdn.net/images/cover/e237cedbbecf26c383d6a3e240408644/0x1900-000000-80-0-0.jpg",
          albumPerformer: "BIBI",
          albumName: "Album - Life is a Bi…",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2021-05-21",
          tracks: [
            {
              id: "bibi_LIAB01",
              avatar:
                "https://cdns-images.dzcdn.net/images/cover/e237cedbbecf26c383d6a3e240408644/0x1900-000000-80-0-0.jpg",
              type: "Album",
              title: "Umm…Life",
              mainMusicMaker: "BIBI",
              stageName: "BIBI",
              name: "Album - Life is a Bi…",
              genre: "Pop",
              releaseDay: "2023-11-08",
              streamed: 2385,
              trend: false,
              link: mp3Type[
                `MusicMaker/BIBI/albums/Life is a Bi…/BIBI비비  Umm Life`
              ],
              lyric: "",
            },
            {
              id: "bibi_LIAB02",
              type: "Album",
              title: "BAD SAD AND MAD",
              mainMusicMaker: "BIBI",
              stageName: "BIBI",
              name: "Album - Life is a Bi…",
              genre: "RnB",
              releaseDay: "2023-11-08",
              streamed: 3325,
              trend: false,
              link: mp3Type[
                `MusicMaker/BIBI/albums/Life is a Bi…/BIBI비비  BAD SAD AND MAD`
              ],
              lyric: "",
            },
            {
              id: "bibi_LIAB03",
              type: "Album",
              title: "PIRI The Dog",
              mainMusicMaker: "BIBI",
              stageName: "BIBI",
              name: "Album - Life is a Bi…",
              genre: "RnB",
              releaseDay: "2023-11-08",
              streamed: 3578,
              trend: false,
              link: mp3Type[
                `MusicMaker/BIBI/albums/Life is a Bi…/PIRI the dog 피리 PIRI the dog`
              ],
              lyric: "",
            },
            {
              id: "bibi_LIAB04",
              type: "Album",
              title: "Birthday Cake",
              mainMusicMaker: "BIBI",
              stageName: "BIBI",
              name: "Album - Life is a Bi…",
              genre: "RnB",
              releaseDay: "2023-11-08",
              streamed: 2395,
              trend: false,
              link: mp3Type[
                `MusicMaker/BIBI/albums/Life is a Bi…/Birthday Cake Birthday Cake`
              ],
              lyric: "",
            },
            {
              id: "bibi_LIAB05",
              title: "Life is a Bi...",
              mainMusicMaker: "BIBI",
              stageName: "BIBI",
              genre: "RnB",
              releaseDay: "2023-11-08",
              streamed: 1238,
              trend: false,
              link: mp3Type[
                `MusicMaker/BIBI/albums/Life is a Bi…/BIBI 비비  인생은 나쁜X Life is a Bi`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "PMQ",
      makerAvatar:
        "https://cdn.tuoitre.vn/zoom/700_700/471584752817336320/2023/9/30/phan-manh-quynh-2-nvcc-1647595826560676316986-205-0-976-1473-crop-1696035354773707165885.jpg",
      makerName: "Phan Mạnh Quỳnh",
      role: "musician" + "/" + "singer",
      priority: true,
      singles: [
        {
          id: "pmq_SauLoiTuKhuoc",
          avatar:
            "https://photo-resize-zmp3.zmdcdn.me/w256_r1x1_jpeg/cover/e/d/0/7/ed0741228ad36870e13624120474e50a.jpg",
          title: "Sau lời từ khước",
          mainMusicMaker: "Phan Mạnh Quỳnh",
          stageName: "Phan Mạnh Quỳnh",
          type: "Single",
          genre: "Pop/Ballad",
          releaseDay: "2024-10-03",
          streamed: 3049,
          trend: true,
          link: mp3Type[
            `MusicMaker/Phan Manh Quynh/singletracks/Sau lời từ khước OST MAI  Phan Mạnh Quỳnh`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "Eminem",
      makerAvatar: "https://avatarfiles.alphacoders.com/174/174632.jpg",
      makerName: "Eminem",
      role: "rapper",
      priority: false,
      singles: [
        {
          id: "em_KillShot",
          avatar:
            "https://upload.wikimedia.org/wikipedia/en/1/15/Eminem_Killshot.jpg",
          title: "KILLSHOT",
          mainMusicMaker: "Eminem",
          stageName: "Eminem",
          type: "Single",
          genre: "Rap/HipHop",
          releaseDay: "2024-10-06",
          streamed: 119935632,
          trend: false,
          link: mp3Type[`MusicMaker/Eminem/singletracks/Eminem - KILLSHOT`],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "EM_Infinite",
          albumAvatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwcAqv_T5ey2mfFEyLcXe3o7VASzb7K825OQ&s",
          albumPerformer: "Eminem",
          albumName: "Album - Infinite",
          mode: "AlbumList",
          rating: "rating",
          rate: 4.5,
          albumType: "Album",
          releaseDay: "1996-11-12",
          tracks: [
            {
              id: "em_inf01",
              avatar:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwcAqv_T5ey2mfFEyLcXe3o7VASzb7K825OQ&s",
              type: "Album",
              title: "Infinite",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Infinite",
              genre: "Rap/HipHop",
              releaseDay: "",
              streamed: 6132852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Infinite/Eminem  Infinite`
              ],
              lyric: "",
            },
            {
              id: "em_inf02",
              type: "Album",
              title: "Infinite (FBT Remix)",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Infinite",
              genre: "Rap/HipHop",
              releaseDay: "",
              streamed: 5321852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Infinite/Eminem  Infinite FBT Remix`
              ],
              lyric: "",
            },
          ],
        },
        {
          id: "EM_Encore",
          albumAvatar:
            "https://upload.wikimedia.org/wikipedia/en/b/b4/Encore_%28Eminem_album%29_coverart.jpg",
          albumPerformer: "Eminem",
          albumName: "Album - Encore",
          mode: "AlbumList",
          rating: "rating",
          rate: 4.5,
          albumType: "Album",
          releaseDay: "2004-12-24",
          tracks: [
            {
              id: "em_encore01",
              avatar:
                "https://upload.wikimedia.org/wikipedia/en/b/b4/Encore_%28Eminem_album%29_coverart.jpg",
              type: "Album",
              title: "Like Toy Soldiers",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Encore",
              genre: "Rap/HipHop",
              releaseDay: "2004-12-24",
              streamed: 4325951,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Encore/Eminem  Like Toy Soldiers`
              ],
              lyric: "",
            },
            {
              id: "em_encore02",
              type: "Album",
              title: "Just Lose It",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Encore",
              genre: "Rap/HipHop",
              releaseDay: "2004-12-24",
              streamed: 2852654,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Encore/Eminem  Just Lose It`
              ],
              lyric: "",
            },
            {
              id: "em_encore03",
              type: "Album",
              title: "A Like That Super",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Encore",
              genre: "Rap/HipHop",
              releaseDay: "2004-12-24",
              streamed: 932654,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Encore/Eminem  A Like That Super`
              ],
              lyric: "",
            },
            {
              id: "em_encore04",
              type: "Album",
              title: "Mockingbird",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Encore",
              genre: "Rap/HipHop",
              releaseDay: "2004-12-24",
              streamed: 8321852,
              trend: true,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Encore/Eminem  Mockingbird`
              ],
              lyric: "",
            },
          ],
        },
        {
          id: "The_Eminem_Show",
          albumAvatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvzhz649VDzgSfhxy-x5KfU4JjggfTe_tEJz0bIbhd3-paHNprUKcJI3Fe6ud-7lx0PJk&usqp=CAU",
          albumPerformer: "Eminem",
          albumName: "Album - The Eminem Show",
          mode: "AlbumList",
          rating: "rating",
          rate: 4.5,
          albumType: "Album",
          releaseDay: "2002-05-21",
          tracks: [
            {
              id: "em_temshow01",
              avatar:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvzhz649VDzgSfhxy-x5KfU4JjggfTe_tEJz0bIbhd3-paHNprUKcJI3Fe6ud-7lx0PJk&usqp=CAU",
              type: "Album",
              title: "White America",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 2753951,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  White America`
              ],
              lyric: "",
            },
            {
              id: "em_temshow02",
              type: "Album",
              title: "Cleanin' Out My Closet",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 9321852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  Cleanin Out My Closet`
              ],
              lyric: "",
            },
            {
              id: "em_temshow03",
              type: "Album",
              title: "Without Me",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 10328523,
              trend: true,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  Without Me`
              ],
              lyric: "",
            },
            {
              id: "em_temshow04",
              type: "Album",
              title: "Sing for the Moment",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 2095634,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  Sing for the Moment`
              ],
              lyric: "",
            },
            {
              id: "em_temshow05",
              type: "Album",
              title: "Hailie's Song",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 654325,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  Hailies Song`
              ],
              lyric: "",
            },
            {
              id: "em_temshow06",
              type: "Album",
              title: "Till I Collapse",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Nate Dogg",
              name: "Album - The Eminem Show",
              genre: "Rap/HipHop",
              releaseDay: "2002-05-21",
              streamed: 3852654,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/TheEminemShow/Eminem  Till I Collapse feat Nate Dogg`
              ],
              lyric: "",
            },
          ],
        },
        {
          id: "EM_Relapse",
          albumAvatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZ08XRYRtFkYAF1Cl9h8PqjEi67SfPBY7dA&s",
          albumPerformer: "Eminem",
          albumName: "Album - Relapse",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2009-09-15",
          tracks: [
            {
              id: "em_repl01",
              avatar:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmZ08XRYRtFkYAF1Cl9h8PqjEi67SfPBY7dA&s",
              type: "Album",
              title: "3 am",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Relapse",
              genre: "Rap/HipHop",
              releaseDay: "2009-09-15",
              streamed: 1085321,
              trend: false,
              link: mp3Type[`MusicMaker/Eminem/albums/Relapse/Eminem  3 am`],
              lyric: "",
            },
            {
              id: "em_repl02",
              type: "Album",
              title: "We Made You",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Relapse",
              genre: "Rap/HipHop",
              releaseDay: "2009-09-15",
              streamed: 951854,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Relapse/Eminem  We Made You`
              ],
              lyric: "",
            },
            {
              id: "em_repl03",
              type: "Album",
              title: "Beautiful",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Relapse",
              genre: "Rap/HipHop",
              releaseDay: "2009-09-15",
              streamed: 1325735,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Relapse/Eminem  Beautiful`
              ],
              lyric: "",
            },
            {
              id: "em_repl04",
              type: "Album",
              title: "Crack a Bottle",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. 50 Cent, Dr Dre",
              name: "Album - Relapse",
              genre: "Rap/HipHop",
              releaseDay: "2009-09-15",
              streamed: 2058792,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Relapse/Eminem  Crack a Bottle feat 50 Cent  Dr Dre`
              ],
              lyric: "",
            },
            {
              id: "em_repl05",
              type: "Album",
              title: "My Darling",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Relapse",
              genre: "Rap/HipHop",
              releaseDay: "2009-09-15",
              streamed: 453222,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Relapse/Eminem  My Darling`
              ],
              lyric: "",
            },
          ],
        },
        {
          id: "EM_Recovery",
          albumAvatar:
            "https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg",
          albumPerformer: "Eminem",
          albumName: "Album - Recovery",
          mode: "AlbumList",
          rating: "rating",
          rate: 4.5,
          albumType: "Album",
          releaseDay: "2010-06-18",
          tracks: [
            {
              id: "em_reco01",
              avatar:
                "https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg",
              type: "Album",
              title: "Not Afraid",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Recovery",
              genre: "Rap/HipHop",
              releaseDay: "2010-06-18",
              streamed: 12369157,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Recovery/Eminem  Not Afraid`
              ],
              lyric: "",
            },
            {
              id: "em_reco02",
              type: "Album",
              title: "Space Bound",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Recovery",
              genre: "Rap/HipHop",
              releaseDay: "2010-06-18",
              streamed: 5321852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Recovery/Eminem  Space Bound`
              ],
              lyric: "",
            },
            {
              id: "em_reco03",
              type: "Album",
              title: "No Love",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Lil Wayne",
              name: "Album - Recovery",
              genre: "Rap/HipHop",
              releaseDay: "2010-06-18",
              streamed: 6321852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Recovery/Eminem  No Love feat Lil Wayne`
              ],
              lyric: "",
            },
            {
              id: "em_reco04",
              type: "Album",
              title: "Love the Way You Lie",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Rihanna",
              name: "Album - Recovery",
              genre: "Rap/HipHop",
              releaseDay: "2010-06-18",
              streamed: 15321854,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Recovery/Eminem  Love the Way You Lie feat Rihanna`
              ],
              lyric: "",
            },
          ],
        },
        {
          id: "EM_Revival",
          albumAvatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrpMJozqst-MyDuXtBcQ6TYH3f_JrztdwTIIMfuw65eOdmnQhEv7hB3Dv4z743qk1rdyc&usqp=CAU",
          albumPerformer: "Eminem",
          albumName: "Album - Revival",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2017-12-15",
          tracks: [
            {
              id: "em_revi01",
              avatar:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrpMJozqst-MyDuXtBcQ6TYH3f_JrztdwTIIMfuw65eOdmnQhEv7hB3Dv4z743qk1rdyc&usqp=CAU",
              type: "Album",
              title: "Walk On Water",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Beyoncé",
              name: "Album - Revival",
              genre: "Rap/HipHop",
              releaseDay: "2017-12-15",
              streamed: 321852,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Revival/Eminem  Walk On Water ft Beyoncé`
              ],
              lyric: "",
            },
            {
              id: "em_revi02",
              type: "Album",
              title: "Believe",
              mainMusicMaker: "Eminem",
              stageName: "Eminem",
              name: "Album - Revival",
              genre: "Rap/HipHop",
              releaseDay: "2017-12-15",
              streamed: 132854,
              trend: false,
              link: mp3Type[`MusicMaker/Eminem/albums/Revival/Eminem  Believe`],
              lyric: "",
            },
            {
              id: "em_revi03",
              type: "Album",
              title: "River",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Ed Sheeran",
              name: "Album - Revival",
              genre: "Rap/HipHop",
              releaseDay: "2017-12-15",
              streamed: 999224,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Revival/Eminem  River ft Ed Sheeran`
              ],
              lyric: "",
            },
            {
              id: "em_revi04",
              type: "Album",
              title: "Nowhere Fast",
              mainMusicMaker: "Eminem",
              stageName: "Eminem ft. Kehlani",
              name: "Album - Revival",
              genre: "Rap/HipHop",
              releaseDay: "2017-12-15",
              streamed: 9324,
              trend: false,
              link: mp3Type[
                `MusicMaker/Eminem/albums/Revival/Eminem  Nowhere Fast ft Kehlani`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "KennyPrice",
      makerAvatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYRSqEftvxjBr-a47iEWe9CPQ_pZ9Q8ocn8uy9Demjcdj1cWFw3y7nySaAgVZ8Pu8jawM&usqp=CAU",
      makerName: "Kenny Price",
      role: "musician" + "/" + "singer",
      priority: false,
      singles: [
        {
          id: "kp_THW",
          avatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnieVqXzgRDxD2DZcmXQjnDAI7cETRYD2hdA&s",
          title: "The HeavyWeight",
          mainMusicMaker: "Kenny Price",
          stageName: "Kenny Price",
          type: "Single",
          genre: "Country",
          releaseDay: "2024-10-12",
          streamed: 666,
          trend: false,
          link: mp3Type[
            `MusicMaker/Kenny Price/singletracks/TheHeavyWeight-Kenny Price`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "TheSouthernRamBlers",
      makerAvatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6C51OUnln1YzmWxyV4ZYxCLDgnnMSZPUt3A&s",
      makerName: "The Southern RamBlers",
      role: "musician" + "/" + "singer",
      priority: false,
      singles: [
        {
          id: "TSR_CR",
          avatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQnqK4XzbJZxveM9f3yeN1fdOrE1dE-scufg&s",
          title: "Country Roads",
          mainMusicMaker: "The Southern RamBlers",
          stageName: "The Southern RamBlers",
          type: "Single",
          genre: "Country",
          releaseDay: "2024-10-03",
          streamed: 325,
          trend: true,
          link: mp3Type[
            `MusicMaker/The Southern RamBlers/singletracks/Country Roads - The Southern RamBlers`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "JackHarlow",
      makerAvatar:
        "https://i.scdn.co/image/ab6761610000e5ebb645c02cfa05103299775097",
      makerName: "Jack Harlow",
      role: "rapper",
      priority: false,
      singles: [
        {
          id: "LOM_JH",
          avatar:
            "https://i1.sndcdn.com/artworks-zNtihhLynoXyysS2-uKqohg-t500x500.jpg",
          title: "Lovin' On Me",
          mainMusicMaker: "Jack Harlow",
          stageName: "Jack Harlow",
          type: "Single",
          genre: "HipHop",
          releaseDay: "2024-02-12",
          streamed: 128523,
          trend: true,
          link: mp3Type[
            `MusicMaker/Jack Harlow/singletracks/Jack Harlow  Lovin On Me`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "MIN",
      makerAvatar:
        "https://vcdn1-giaitri.vnecdn.net/2022/03/05/MIN2-1646448104-6583-1646449221.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=HpgQwfSaYVU6yRDg_emSZw",
      makerName: "MIN",
      role: "singer",
      priority: true,
      singles: [
        {
          id: "min_Ghen",
          avatar:
            "https://i.scdn.co/image/ab67616d0000b273a29c93370755f839ace4c877",
          title: "GHEN",
          mainMusicMaker: "MIN",
          stageName: "KHẮC HƯNG x ERIK x MIN",
          type: "Single",
          genre: "Pop",
          releaseDay: "2024-10-12",
          streamed: 58522,
          trend: true,
          link: mp3Type[
            `MusicMaker/MIN/singletracks/KHẮC HƯNG x MIN x ERIK  Ghen`
          ],
          lyric: "",
        },
      ],
      albums: [
        {
          id: "50/50",
          albumAvatar:
            "https://i.scdn.co/image/ab67616d0000b273221013fb2e16046539cfbdd8",
          albumPerformer: "MIN",
          albumName: "Album - 50|50",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2022-05-20",
          tracks: [
            {
              id: "min_505001",
              avatar:
                "https://i.scdn.co/image/ab67616d0000b273221013fb2e16046539cfbdd8",
              type: "Album",
              title: "Cà Phê",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 2315,
              trend: true,
              link: mp3Type[`MusicMaker/MIN/albums/5050/MIN  CÀ PHÊ`],
              lyric: "",
            },
            {
              id: "min_505002",
              type: "Album",
              title: "Trên Tình Bạn Dưới Tình Yêu",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 3678,
              trend: true,
              link: mp3Type[
                `MusicMaker/MIN/albums/5050/MIN  TRÊN TÌNH BẠN DƯỚI TÌNH YÊU`
              ],
              lyric: "",
            },
            {
              id: "min_505003",
              type: "Album",
              title: "Anh Qua Đây Đi",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 1035,
              trend: false,
              link: mp3Type[
                `MusicMaker/MIN/albums/5050/MIN  ANH QUA ĐÂY ĐI OFFICIAL AUDIO`
              ],
              lyric: "",
            },
            {
              id: "min_505004",
              type: "Album",
              title: "Phải Lòng Anh",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 1285,
              trend: false,
              link: mp3Type[`MusicMaker/MIN/albums/5050/MIN  PHẢI LÒNG ANH`],
              lyric: "",
            },
            {
              id: "min_505005",
              type: "Album",
              title: "Ngắm Sao (Dear Mintacs)",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 935,
              trend: false,
              link: mp3Type[
                `MusicMaker/MIN/albums/5050/MIN  NGẮM SAO DEAR MINIACS`
              ],
              lyric: "",
            },
            {
              id: "min_505006",
              type: "Album",
              title: "Watching The Stars",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 935,
              trend: false,
              link: mp3Type[
                `MusicMaker/MIN/albums/5050/MIN  WATCHING THE STARS`
              ],
              lyric: "",
            },
            {
              id: "min_505007",
              type: "Album",
              title: "Phải Lòng Anh (Dream Ver)",
              mainMusicMaker: "MIN",
              stageName: "MIN",
              name: "Album - 50|50",
              genre: "Pop",
              releaseDay: "2022-05-20",
              streamed: 825,
              trend: false,
              link: mp3Type[
                `MusicMaker/MIN/albums/5050/MIN  PHẢI LÒNG ANH DREAM VER`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "IDs",
      makerAvatar:
        "https://www.coca-cola.com/content/dam/onexp/global/central/offerings/coke-studio/artists/2_Imagine_Dragons_by_Eric_Ray_Davidson_GREEN_04_1-1.jpg",
      makerName: "Imagine Dragons",
      role: "band",
      priority: true,
      singles: [
        {
          id: "IMGDG_Bones",
          avatar: "https://i.ytimg.com/vi/DYed5whEf4g/maxresdefault.jpg",
          title: "Bones",
          mainMusicMaker: "Imagine Dragons",
          stageName: "Imagine Dragons",
          type: "Single",
          genre: "Pop",
          releaseDay: "2022-04-06",
          streamed: 335684,
          trend: true,
          link: mp3Type[
            `MusicMaker/Imagine Dragons/singletracks/Imagine Dragons  Bones`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "SHw",
      makerAvatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTuY4CVBBHNls0TTOtiGxAtdKSiFHj1Xecaw&s",
      makerName: "Sleepy Hallow",
      role: "singer",
      priority: false,
      singles: [
        {
          id: "SHw_Marie",
          avatar: "https://i1.sndcdn.com/artworks-shwzMchg0r4r-0-t500x500.jpg",
          title: "Marie",
          mainMusicMaker: "Sleepy Hallow",
          stageName: "Sleepy Hallow",
          type: "Single",
          genre: "Pop",
          releaseDay: "2022-11-02",
          streamed: 235584,
          trend: true,
          link: mp3Type[
            `MusicMaker/Sleepy Hallow/singletracks/Sleepy Hallow  Marie`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "J.Cole",
      makerAvatar:
        "https://hips.hearstapps.com/hmg-prod/images/j_cole_photo_by_isaac_brekken_wireimage_getty_503069628.jpg?crop=1xw:1.0xh;center,top&resize=640:*",
      makerName: "J.Cole",
      role: "rapper" + "/" + "musicProducer",
      priority: false,
      singles: [
        {
          id: "jc_sn",
          avatar: "https://i.ytimg.com/vi/-RhwxYTKDWU/maxresdefault.jpg",
          title: "She Knows",
          mainMusicMaker: "J.Cole",
          stageName: "J.Cole",
          type: "Single",
          genre: "HipHop/Rap",
          releaseDay: "2022-10-02",
          streamed: 22423724,
          trend: true,
          link: mp3Type[`MusicMaker/J.Cole/singletracks/JColeSheKnows`],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "YOASOBI",
      makerAvatar:
        "https://kilala.vn/data/uploads/2024/111020240958-1728615533-yoasobi.jfif",
      makerName: "YOASOBI",
      role: "band",
      priority: false,
      singles: [
        {
          id: "Yo_Ta",
          avatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp_QtMn9NkfZk3gYn4sOxZF9uzk7ljyCu7qw&s",
          title: "Tabun",
          mainMusicMaker: "YOASOBI",
          stageName: "YOASOBI",
          type: "Single",
          genre: "Pop",
          releaseDay: "2022-10-01",
          streamed: 135151500,
          trend: true,
          link: mp3Type[`MusicMaker/YOASOBI/singletracks/YOASOBIたふん`],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "Hanumankind",
      makerAvatar:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMgQIZ3Nnsq2JdX8WgHjuZ3X9BacgqfcoCHQ&s",
      makerName: "Hanumankind",
      role: "rapper",
      priority: false,
      singles: [
        {
          id: "huKal_BD",
          avatar:
            "https://i1.sndcdn.com/artworks-pXXG0Ja29z1c0RXB-PVcoqQ-t500x500.jpg",
          title: "Big Dawgs",
          mainMusicMaker: "Hanumankind",
          stageName: "Hanumankind Ft. Kalmi",
          type: "Single",
          genre: "Pop",
          releaseDay: "2023-10-01",
          streamed: 177885500,
          trend: true,
          link: mp3Type[
            `MusicMaker/Hanumankind/singletracks/HanumankindBigDawgsKalmi`
          ],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "AMEE",
      makerAvatar:
        "https://duyendangvietnam.net.vn/public/uploads/file1s/pv_Thanh_Toan/ava(236).jpg",
      makerName: "AMEE",
      role: "singer",
      priority: false,
      singles: [],
      albums: [
        {
          id: "dre_AMEE",
          albumAvatar:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDO4wFtKDQjloQB1TvhnpAJY838VyIwzKT7g&s",
          albumPerformer: "AMEE",
          albumName: "Album - dreAMEE",
          mode: "AlbumList",
          rating: "rating",
          rate: 4,
          albumType: "Album",
          releaseDay: "2019-04-03",
          tracks: [
            {
              id: "dre_A01",
              type: "Album",
              title: "Anh Nhả Ở Đâu Thế",
              avatar:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDO4wFtKDQjloQB1TvhnpAJY838VyIwzKT7g&s",
              mainMusicMaker: "AMEE",
              stageName: "AMEE x BRAY",
              name: "Album - dreAMEE",
              genre: "Pop",
              releaseDay: "2019-04-03",
              streamed: 139143651,
              trend: false,
              link: mp3Type[`MusicMaker/AMEE/albums/dreAMEE/AMEExB RAY-ANODT`],
              lyric: "",
            },
            {
              id: "dre_A02",
              type: "Album",
              title: "Ex's Hate Me (Part 2)",
              mainMusicMaker: "AMEE",
              stageName: "AMEE x BRAY",
              name: "Album - dreAMEE",
              genre: "Acoustic",
              releaseDay: "2020-07-22",
              streamed: 42120600,
              trend: false,
              link: mp3Type[
                `MusicMaker/AMEE/albums/dreAMEE/AMEExBRAYExsHateMeP2`
              ],
              lyric: "",
            },
            {
              id: "dre_A03",
              type: "Album",
              title: "SAO ANH CHƯA VỀ NHÀ",
              mainMusicMaker: "AMEE",
              stageName: "AMEE ft. RICKY STAR",
              name: "Album - dreAMEE",
              genre: "Pop",
              releaseDay: "2023-08-25",
              streamed: 66401200,
              trend: false,
              link: mp3Type[
                `MusicMaker/AMEE/albums/dreAMEE/AMEESACVNftRICKYSTAR`
              ],
              lyric: "",
            },
          ],
        },
      ],
    },
    {
      id: "BichPhuong",
      makerAvatar:
        "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/1/25/bich-phuong-1-1643113353899263889600.jpg",
      makerName: "BÍCH PHƯƠNG",
      role: "singer",
      priority: false,
      singles: [
        {
          id: "bphuong_byeu",
          avatar:
            "https://photo-resize-zmp3.zadn.vn/w600_r1x1_jpeg/cover/3/c/d/5/3cd5abfdd0224a98757fef8707344077.jpg",
          title: "Bùa Yêu",
          mainMusicMaker: "BÍCH PHƯƠNG",
          stageName: "BÍCH PHƯƠNG",
          type: "Single",
          genre: "Pop",
          releaseDay: "2019-10-01",
          streamed: 132650721,
          trend: false,
          link: mp3Type[`MusicMaker/Bich Phuong/singletracks/BÍCHPHƯƠNGBùaYêu`],
          lyric: "",
        },
        {
          id: "bphuong_bglc",
          avatar: "https://kenh14cdn.com/2017/4-1513186582381.jpg",
          title: "Bao Giờ Lấy Chồng?",
          mainMusicMaker: "BÍCH PHƯƠNG",
          stageName: "BÍCH PHƯƠNG",
          type: "Single",
          genre: "Pop",
          releaseDay: "2017-01-16",
          streamed: 100170075,
          trend: false,
          link: mp3Type[
            `MusicMaker/Bich Phuong/singletracks/BPBao Giờ Lấy Chồng`
          ],
          lyric: "",
        },
        {
          id: "bphuong_ncts",
          avatar: "https://i.ytimg.com/vi/sU8G7Q4rUA4/maxresdefault.jpg",
          title: "Nâng Chén Tiêu Sầu",
          mainMusicMaker: "BÍCH PHƯƠNG",
          stageName: "BÍCH PHƯƠNG",
          type: "Single",
          genre: "House",
          releaseDay: "2017-01-16",
          streamed: 20231593,
          trend: false,
          link: mp3Type[`MusicMaker/Bich Phuong/singletracks/BPhuongNCTS`],
          lyric: "",
        },
      ],
      albums: [],
    },
    {
      id: "roSE",
      makerAvatar:
        "https://nqs.1cdn.vn/thumbs/540x360/2024/10/27/image.tienphong.vn-uploaded-2024-athlraungenat-2024_10_27-_463989725-1260720248449971-1746876593578460535-n-5179.jpg",
      makerName: "ROSÉ",
      role: `singer`,
      priority: false,
      singles: [
        {
          id: "roBruAPT",
          avatar:
            "https://avatar-ex-swe.nixcdn.com/song/2024/10/18/1/8/a/e/1729211353297_640.jpg",
          title: "APT",
          mainMusicMaker: "ROSÉ",
          stageName: "ROSÉ ft. Bruno Mars",
          type: "Single",
          genre: "Pop",
          releaseDay: "2024-10-18",
          streamed: 568445734,
          trend: true,
          link: mp3Type[`MusicMaker/ROSE/singletracks/APT`],
          lyric: "",
        },
      ],
      albums: [],
    },
  ],
  getMusicMaker: function () {
    return this.musicMakerList;
  },
};

export default apiMusicMaker;
